//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Domain.Message.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Domain.Message.Email.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EmailTemplate&gt;
        ///&lt;Subject&gt;@stopper@ has resumed the @line@ line&lt;/Subject&gt;
        ///&lt;BodyHtml&gt;   
        ///
        ///&lt;![CDATA[
        ///
        ///
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            width: 100% !important;
        ///            font-family: Arial;
        ///            font-size: 10px;
        ///            -webkit-tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EmailTemplate&gt;
        ///&lt;Subject&gt;@stopper@ has stopped the @line@ line&lt;/Subject&gt;
        ///&lt;BodyHtml&gt;   
        ///
        ///&lt;![CDATA[
        ///
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            width: 100% !important;
        ///            font-family: Arial;
        ///            font-size: 10px;
        ///            -webkit-text- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EmailTemplate&gt;
        ///  &lt;Subject&gt;Welcome to Stop The Line&lt;/Subject&gt;
        ///  &lt;BodyHtml&gt;
        ///
        ///    &lt;![CDATA[
        ///
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            width: 100% !important;
        ///            font-family: Arial;
        ///            font-size: 10px;
        ///            -webkit-text-size-adj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TenantCreated {
            get {
                return ResourceManager.GetString("TenantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;EmailTemplate&gt;
        ///  &lt;Subject&gt;Invitation to @org@ by @inviter@&lt;/Subject&gt;
        ///  &lt;BodyHtml&gt;
        ///
        ///    &lt;![CDATA[
        ///
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            width: 100% !important;
        ///            font-family: Arial;
        ///            font-size: 10px;
        ///            -webkit-text- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserInvite {
            get {
                return ResourceManager.GetString("UserInvite", resourceCulture);
            }
        }
    }
}
